version: '3.8'
services:
  postgres:
    container_name: postgresServer
    image: postgres:13
    networks:
      - backend-local-networks
    environment:
      POSTGRES_PASSWORD: admin123456
      POSTGRES_USER: admin
      POSTGRES_DB: KovyMartDb
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5051:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadminContainer
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=hai@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
        - 5050:80
    networks:
        - backend-local-networks
    restart: unless-stopped
networks:
  backend-local-networks:
volumes:
  pgdata:
